version: '3'
services:
    ereina:
        build: .
        command: Ereina
        expose:
            - "2319"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - ereina
